### ISSUE TITLE
Export: Optional filename separator

### ISSUE THREAD

**Issue by Larpon** [GDquest/GDquest-art-tools#20]
I'd be nice to have an input box option for changing the white space separator to something custom.
AFAIK all Kritas supported platforms can handle white space in the filename?

Right now we force the use of `_` instead of just leaving the white spaces as is?

**Comment by razcore-art** [comment]
Yes, we're forcing `_` not just for space, but for any symbol character. I personally prefer `_` over space any time, but let's see what Nathan has to say.

**Comment by NathanLovato** [comment]
I'd rather leave _ as a replacement for any symbol. Keep it simple. whitespace in file names is a bad habit imo, it makes it harder to work with command line programs.

In general, I want our tools to provide sane defaults, ideally good UX, and minimal customization options when we can't do otherwise. To avoid extra maintenance and sources of bugs, considering how few devs will contribute compared to the many persons who use them, and our limited resources.

**Comment by Larpon** [comment]
Enforcing a specific separation character is bad UX in my opinion. People should have the freedom to use what ever they like in their asset pipeline given their platform support it.

Not everyone uses `_`. Many uses `-` as well or maybe even a mix of different characters to mark their files (just like we enforce `sXXX` and `mXXX` in the exported file names. See my thoughts on #19 ).

I'm all in favour of keeping things simple, don't get me wrong - but provide advanced options for advanced users and/or users with special needs, Like most FOSS projects traditionally do. String replacement usually isn't very bug introducing in any language so I don't see a sea of bugs with this particular thing.

Move such stuff to a default collapsed "Advanced options" grouping in the UI or a menu item if we can hook into that :) That way people have the freedom to choose.

I do know this might be aimed at designers etc. - but so far the feature set is also very useful for game developers (like me).

**Comment by NathanLovato** [comment]
> so I don't see a sea of bugs with this particular thing

I never said that. I want us to avoid extra code, maintenance work, and sources of bugs in general.

Enforcing a character isn't providing a bad user experience until someone really *needs* the alternative. I don't think people should have the freedom to do anything they could imagine or many options. Just the options that cover their *needs*.

I wouldn't take the average FOSS app as an example when it comes to user experience. Not that we're great in this regard: it takes a lot of work, thought, and experience using the tool(s) in production.

If you want to add these options and you're willing to maintain your code, it's welcome! But I don't want to add options we don't need for hypothetical future use cases or hypothetical future users.

Then, if you're going to add options like these, to use special characters, you'll likely want to:

- Set it for entire projects, not just per document. So you'll want to store some plugin config somewhere
- Maybe you'll want to override your config per document?

I'm okay adding options like these and extra tools, e.g. your much welcome COA support, if someone contributes them. We have too much work to do to add options we don't need for GDquest or our own projects.

**Comment by razcore-art** [comment]
Nathan's views are pretty much in line with mine, I just didn't go into the depth of it since he has the last say anyway :)

The use of `_` is very simple: it's the symbol that resembles SPACE the most and it isn't treated as a special character in terminals, that's why *I* personally prefer `_` over any other character such as `-`. But this is really just nitpicking, I think if the tool gives you sane defaults that don't interfere with your work, but even provide good ways of organizing stuff without you having to manually move things around then it does its job.

Extra stuff is well... extra.

**Comment by NathanLovato** [comment]
To clarify the point above: I don't want to anticipate the hypothetical wishes of hypothetical future users. When it comes to Foss tools like we do, I want us to focus on supporting actual users and solving problems enough persons are facing or faced. Especially when we're doing the work benevolently for others. Because we have limited resources, time...

Then, contributors are more than welcome 🙂

**Comment by Larpon** [comment]
Heh, I won't go further with this then - time will tell.

A layer named `Robot-arm-L` than ends up `Robot_arm_L.png` upon export is just illogical

**Comment by NathanLovato** [comment]
> A layer named Robot-arm-L than ends up Robot_arm_L.png upon export is just illogical

This isn't what this discussion was about. We were talking about adding an option to let the user choose the separation character in the files' name.

This seems like a bug to me. I'd expect the filename to end up as e.g. `Robot-arm-L_s50`. @razcore-art, what do you think?

**Comment by razcore-art** [comment]
Yeah, maybe I was too aggressive in the way I treat symbols, I just ended up replacing everything with `_` because it was simpler to do, being alpha and all, maybe we should discuss what symbols *are* allowed and make exceptions for those.

**Comment by NathanLovato** [comment]
Okay, we can have a new issue for that then 😄

**Comment by Larpon** [comment]
> This isn't what this discussion was about. We were talking about adding an option to let the user choose the separation character in the files' name

Exactly - so I could input something else to change the (in my case) unwanted renaming behaviour (`_` above all other) :smile: - I was unclear and thought of a broader solution for the specific "bug", my bad! #21 is a good start :+1:
