### ISSUE TITLE
Metadata update overwriting layer names instead of appending

### ISSUE THREAD

**Issue by Seltonu** [GDquest/GDquest-art-tools#65]
**I'm submitting a...**

- [X] Bug report.

## Bug report ##

**What is the current behavior?**
Using t=false in batch exporter renames layers innapropriately. Example the layer name "retry" becomes "refalsery", because the t in the middle of the word is overwritten. Did not test with other metadata tags, unknown if only affects "t"

**What is the expected behavior?**
Layer name will not be altered.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Create a layer with the name retry
2. Update metadata of layer to t=false

Layers after updating metadata:
![image](https://user-images.githubusercontent.com/10287568/177238815-f0352bfa-5704-46b1-b89f-63a36d5d638a.png)

**Note** Using Krita 5.0.6 flatpak

**Comment by razcore-rad** [comment]
We fixed a few bugs since version 5.0.6. I can't reproduce the bug with the latest Krita 5.1.0-beta1. So you have a few options:

- install the plugin from this repo instead. It should override the one that comes with Krita.
- grab Krita 5.1.0-beta1 if you're not strict about it being beta
- wait for the next stable release
