### ISSUE TITLE
Export: batch export all layers based on their names

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/GDquest-art-tools#9]
In game art, it's common to need to export assets:

- To a precise relative/absolute path on the file system regardless of their position in the layer tree
- To different scales, e.g. 0.5x or 1x

Krita does not support many layers so I think it'd be best to always use a dedicated document to export assets. In this export document, you'd import your krita files as file layers, allowing you to set up your exports anytime.

In this case, exporting files in a way that reflects the layer tree would be a good default. In Photoshop, generator will instead only export layers that have a file extension in their name.

The tool should also trim exported nodes by default. You can always trick a trimming tool by drawing a 1% opaque, 1px rectangle on your layer (a trick I used in Photoshop), although the best would be being able to draw custom slices bound to layers, which Krita doesn't support:

![designer_2018-12-14_19-42-45](https://user-images.githubusercontent.com/12694995/49998796-8e497e00-ffd8-11e8-8dc6-6ccb427ed01e.png)

The tool should:

- export paint layer nodes using their names, to a default file format (png for games), using the layer's position in the tree. Layer groups act as folders and subfolders
- If there's a file extension in the node's name, use the name as the output path instead

**Comment by NathanLovato** [comment]
@razcore-art we talked about this before. Can you work on a tool to efficiently export sprites in batch based on the layer names, and the group/tree structure? You can use the official batch export plugin that ships with Krita as a reference. 

I'd like a tool we can use a lot faster as in gamedev we often need to export assets, and maybe that can only re-export new named layers and/or layers that changed, not save every asset from scratch.

The idea for the asset pipeline/workflow will be:
- Paint sprites on individual layers or
- Design complex individual sprites in their own .kra files and instance them as file layers in a master/export doc
- Have tools in place to efficiently replace a group of layers with a file layer, see #1 and #2

**Comment by NathanLovato** [comment]
@razcore-art I just updated the task's description. Tell me if you need any more information or a to do list/steps

**Comment by razcore-art** [comment]
Yes, I saw you updated it, thanks a lot, very helpful!

So a tiny report. Today I wreaked my brain the entire time trying to find a solution to parsing the tree structure of the Krita documents. It's... well as you expect, pretty hard to do, especially if you want to repeat operations generically, not just on selected layers. So I went through a lot of iterations, trying to implement algorithms for creating directory structure based on the Krita document structure and it's a mess if you do it "by hand". Luckily I found this neat [anytree](https://anytree.readthedocs.io) module. This brings in some dependencies (anytree & six), but I think it simplifies stuff a lot, well... we'll see when next I'll work on creating the folder structure for exporting.

So far I managed to create the tree structure with [anytree](https://anytree.readthedocs.io):

example:
```
Node('/root', obj=<PyKrita.krita.Node object at 0x7f5d21a41af8>)
├── Node('/root/BKG', obj=<PyKrita.krita.GroupLayer object at 0x7f5d21a41a68>)
│   ├── Node('/root/BKG/BKGDefault', obj=<PyKrita.krita.Node object at 0x7f5d21a4d0d8>)
│   └── Node('/root/BKG/BKGPrimed', obj=<PyKrita.krita.Node object at 0x7f5d21a4d3a8>)
├── Node('/root/GroupBase', obj=<PyKrita.krita.GroupLayer object at 0x7f5d21a4d708>)
│   ├── Node('/root/GroupBase/Base', obj=<PyKrita.krita.Node object at 0x7f5d21a4d678>)
│   └── Node('/root/GroupBase/Signature', obj=<PyKrita.krita.Node object at 0x7f5d21a4da68>)
├── Node('/root/UnsharpMask', obj=<PyKrita.krita.FilterLayer object at 0x7f5d21a4d798>)
├── Node('/root/Noise', obj=<PyKrita.krita.FilterLayer object at 0x7f5d21a4daf8>)
├── Node('/root/ColorAdjustment', obj=<PyKrita.krita.FilterLayer object at 0x7f5d21a4d1f8>)
└── Node('/root/ValueCheck', obj=<PyKrita.krita.FilterLayer object at 0x7f5d21a4d8b8>)
```

**Comment by NathanLovato** [comment]
I don't mind dependencies if they solve a tricky problem or something that'd be time-consuming to reproduce. <100kb is nothing, it's all good

**Comment by razcore-art** [comment]
Bit of progress report.

After having a fresh look and thinking about the tree structure algorithms, I've implemented some very tiny generators for traversing the trees and I'm quite proud of them :)). This means that we don't have to rely on [anytree](https://anytree.readthedocs.io/) any more. 

Today I spent most of the time trying to figure out how to integrate [Pillow](https://pillow.readthedocs.io) and how to use it because as it turns out the documents are pretty crappy when it comes to details. Ok, so the problem with [Pillow](https://pillow.readthedocs.io) is that it's an external dependency that has some C code as well and that means that it has to be compiled for whatever version of Python Krita is using. I have Krita v4.1.7 that's compiled with Python3.5. Unfortunately Python3.5 isn't supported any more on Ubuntu and even if it was, we have to figure out a better way for external dependencies than to ask users to install system wide modules or something like that. I have Python3.7 and it took me a while how to figure out how to download the correct Python3.5 version and make it work. Luckily it's pretty simple (at least on Linux): `pip install --target=/path/to/krita/python/plugin/Dependencies /link/to/pillow/compatible/with/krita/python/interpreter`. Correct [Pillow](https://pillow.readthedocs.io) version can be found from [PyPI Pillow table](https://pypi.org/project/Pillow/#files) but ideally this should be done via an install script or something like that so that the user doesn't have to do it manually.

Next, it took me a while to understand how to convert Krita image data into [Pillow](https://pillow.readthedocs.io) images to be able to manipulate them. In the end I figured out some stuff and did a quick test as you can see in the image.

Next steps are to:
- do exports based on metadata contained in layer names
- do exports for selected layers only

![image](https://user-images.githubusercontent.com/1177508/50110649-74f83a00-0243-11e9-8921-c55cab00ba1a.png)

**Comment by NathanLovato** [comment]
Thanks for the report 🙂

**Comment by NathanLovato** [comment]
Let's start with `e=png` then. Okay for the name :)

**Comment by razcore-art** [comment]
So I hit a bit of a roadblock. First there was a tiny bug in `Node.scaleNode()` making it not callable from Python. That got fixed in the latest nightly build, but there's another problem that I'm not so sure it can be easily fixed.

`Node.scaleNode()` is ran in a separate thread internally which means it doesn't finish immediately and we don't know when it finishes work which mean we can't just apply scale & then save. Tomorrow I'll try to figure out a solution with the devs. If we can't find a solution the option really is Pillow

**Comment by NathanLovato** [comment]
There's no ability to wait for an operation to finish? If any addon uses scale in combination with other tools, like a macro, it'll need the operation to finish before it proceeds with the next.

Regarding pillow, another option is to save everything as 8-bit srgb PNG and to open and scale the resulting files in a second pass.

**Comment by razcore-art** [comment]
No, there's no way to wait for the operations to finish, checked the code, internally these operations are performed via some `KisTransformWorker`, separate thread. Talked with Boudewijn yesterday and he mentioned that the Python API should be sequential so it's a bug. It has to be fixed, but I'm sure it's no easy task.

I think in terms of  coding time, workflow 1: *krita save png -> reopen in pillow -> reparse metadata -> resave* will take pretty much the same time as doing workflow 2: *pillow from start to end*. I also prefer workflow 2 because it's easier to reason about. I was told the Python interpreter runs on the main GUI thread so it's blocking user interaction and so we definitely need to consider doing some operations (if not all) via `multiprocessing` or at the very least some separate thread and that will be easier if we keep it simple.

**Comment by NathanLovato** [comment]
If it already works just supporting one color depth and space that's fine by me. In games you're working for the screen so you want to work with sRGB from the start most of the time. Higher channel bit depth can be useful as they let you do more color manipulations without producing artifacts but it has a performance cost so... supporting just one color space and bit depth is fine by me - contributors can do the research if they want to add more.
